for()
x = input("plz enter your 1st number : ")
y = input("plz enter your 2nd number : ")

x = int(x)
y = int(y)
print("sum ", x+y)
print("sub ", x-y)
print("mul ", x*y)
print("div ", x/y)
print("floar div ", x//y)
print("power ", x ** y)
print(~x)
print(x << 6)
